---
# Created from https://github.com/lando/lando/issues/1723#issuecomment-636544224

# This is always the same... we should use the devshop prepare ansible shell script instead?
- name: Install Python3 Pip
  apt:
    name:
    - python3-pip
    update_cache: yes

# This took like 4-5 minutes!
- name: Install Ansible
  pip:
    name:
    - ansible 

- name: Install Packages
  apt:
    name: 
    - fish
    update_cache: yes

